# This is a basic workflow to help you get started with Actions

name: TypeDoc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  typedoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      # Runs a single command using the runners shell
      - name: init
        run: |
          npm i -g yarn
          yarn install

      # Runs a set of commands using the runners shell
      - name: clear output dir
        run: rm ./docs/type/* -rf
      - name: update .gitignore
        run: sed -i -e '/\/docs\/type/d' .gitignore
      - name: update sample.html
        run: | 
          sed --in-place --expression='s/..\/..\/dist\/bundle.js/https:\/\/cdn.jsdelivr.net\/npm\/@xpadev-net\/niconicomments@latest\/dist\/bundle.min.js/' docs/sample/index.html
          sed --in-place --expression='s/..\/..\/..\/niwango\/dist\/bundle.js/https:\/\/cdn.jsdelivr.net\/gh\/xpadev-net\/niwango.js@dev-build\/dist\/bundle.js/' docs/sample/index.html
      - name: generate typedoc
        run: yarn typedoc

      - name: Create new Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions@xpadev.net"
          git config user.name "github-actions"
          git checkout -b typedoc
          git add .
          git commit -m "auto generate" -n
          git push -f origin typedoc
